sudo: true
language: java
jdk:
  - oraclejdk8
# addons:
#   apt:
#     packages:
#       - oracle-java8-set-default
before_script:
  - sleep 10
script:
  - cd sparrow-parent
  - mvn clean verify -DskipTests
before_install:
  - java -version
  - echo $JAVA_HOME
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.1.1.deb && sudo dpkg -i --force-confnew elasticsearch-5.1.1.deb && sudo service elasticsearch restart